[package]
name = "ormolu_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
ormolu_interfaces = { path = "../ormolu_interfaces" }

[lib]
proc-macro = true
doctest = false
